services:
  stats-db:
    image: postgres:16
    container_name: stats-db
    ports: ["5433:5432"]
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./stats-db/init.sql:/docker-entrypoint-initdb.d/init.sql

  stats-server:
    build: ./ewm-stats-server
    container_name: stats-server
    ports: ["9090:9090"]
    depends_on:
      - stats-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

  main-db:
    image: postgres:16
    container_name: main-db
    ports: [ "5432:5432" ]
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./main-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d main" ]
      interval: 5s
      timeout: 5s
      retries: 10

  ewm-service:
    build: ./ewm-main-service
    container_name: ewm-service
    ports: ["8080:8080"]
    depends_on:
      main-db:
        condition: service_healthy
      stats-server:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://main-db:5432/main
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      STATS_SERVER_URL: http://stats-server:9090
